### ISSUE TITLE
Add Support For MongoDb or Give Examples to do so

### ISSUE THREAD

**Issue by ankurpathak** [quartzdesk/quartzdesk-executor#1]
Quartz Desk Have only supprt for Quartz coonected to SQL Databases. But their are projects which support Quaratz Mongo. Check this url for reference:
https://github.com/michaelklishin/quartz-mongodb
Can we add support for these NoSQL Databases or Api or use Custom Job Store or examples how
to use them with Quartz Desk.

**Comment by xmoravej** [comment]
Hi Ankur,
It should not be a big problem to add support for Mongo to QuartzDesk Executor as long as Quartz supports this database. We will look into this. You are free to submit a patch if you wish to add that support yourself and we will integrate it.

**Comment by ankurpathak** [comment]
@xmoravej Yes I will love to submit a pull request for this. Can you please help me where to start with
some documentation, example or any thing which is related to this issue??

**Comment by xmoravej** [comment]
You will probably want to start by looking into the SpringProfilesActivator class that activates the Quartz database profile using data from the quartzdesk-executor.properties file and work down from there. If you can wait, we can possibly add support for Mongo by the end of September when we will be releasing a new version of QuartzDesk.
Kind regards,
Jan

**Comment by ankurpathak** [comment]
@xmoravej September is not very far, so I will wait for official release.

**Comment by xmoravej** [comment]
Hi Ankur,
I may have misinterpreted your initial request. You asked about QuartzDesk and its support Quartz-based applications that use NoSQL (e.g. MongoDB etc.) job stores. Please note that QuartzDesk supports all types of Quartz job stores because when it interacts with Quartz, it does so through a higher-level APIs that shield it completely from the actual Quartz job store implementation. In other words, you can use QuartzDesk GUI to connect to your Quartz-based application that uses MongoDB as its job store. No changes are required on the QuartzDesk side for this to work.

On the other hand, if you meant adding support for NoSQL databases to QuartzDesk Executor so that the QuartzDesk Executor application itself and its embedded Quartz scheduler uses a NoSQL database, then it is a completely different thing. We reviewed the QuartzDesk Executor code and found out it would require MAJOR refactorings to support both SQL and NoSQL databases.

Could you please clarify what you actually meant? Thank you.

**Comment by ankurpathak** [comment]
Your interpretation is right. I was taking abot Quartz on NoSQL Job Stores. Can we have some sample of NoSQL job store with QuartzDesk.

**Comment by xmoravej** [comment]
If you want to use Quartz with a NoSQL job store, you can maybe check the following blog post that describes Quartz configuration with MongoDB job store:

https://dzone.com/articles/using-quartz-for-scheduling-with-mongodb

As I mentioned, the type of the Quartz job store is completely invisible from the QuartzDesk GUI's (web app) and QuartzDesk JVM Agent's perspective. You can use whatever job store implementation you want. QuartzDesk GUI & Agent never interact with the Quartz job store directly and always use a higher-level Quartz job store API that completely shields them from the job store implementation details.

**Comment by xmoravej** [comment]
Closing this ticket. QuartzDesk Executor cannot support MongoDB at the moment, however, QuartzDesk (our flagship product) supports Quartz schedulers with Mongo DB job stores as QuartzDesk is a completely Quartz job store type-agnostic solution.
